apiVersion: v1
kind: Service
metadata:
  name: python-flask-app-service
spec:
  type: NodePort
  selector:
    app: python-flask-app
  ports:
    - targetPort: 8080
      port: 8002
      nodePort: 30080
